Feature/8 create routine UI
FITNEE/FITNEE_Client_Refactor pull request #10
Opened 2024-05-10 11:09 UTC by sseho

📌**구현기능**
- 루틴생성 전체 플로우 구현, 진행바 애니메이션 수정, 더미데이터 생성

⚒️**작업내용**

- [x] wheelPicker 컴포넌트
- [x] 진행바 20씩 증가
- [x] 부위 선택
- [x] 날짜 선택
- [x] 진행바 100 도달시 페이지 전환
- [x] 루틴 결과
- [x] 제스처 뒤로가기 막기

2024-05-14 17:03 UTC, iOdiO89 requested changes
1. 세부적으로 정의되어 있는 px값들은 최대한 px 값 지켜주고, 여러 화면에 다 대응될 수 있게 큰 덩어리들은 `justify: between` 같은 거로 설정하면 좋을 거 같아요

2. pages, component 폴더 안에 CreateRoutine 폴더 소문자시작하는 거로 바꿔주세요

3. useState 사용할 때 type 명시를 안 하고 쓰는 거 같던데 그래도 오류 안나?? Typescript인 만큼 type 제대로 명시해서 쓰면 좋을 것 같습니당

리뷰내용 수정되면 머지하겠습니다 !!

2024-05-19 06:57 UTC, sseho commented on src/components/CreateRoutine/CreateRoutine3.tsx
> +  height: 87.4%;
수치 고정 하면 화면 비율에 따라 안바뀌는데 괜찮나요..?

2024-06-02 09:10 UTC, sseho commented on src/components/CreateRoutine/WheelPicker.tsx
> +            selectedStyle={{ borderColor: '#E8EBF0', borderWidth: 0.5 }}
엉 없는 값

2024-06-05 08:42 UTC, iOdiO89 approved these changes

2024-06-05 08:42 UTC, merged