Feature/5 home UI
FITNEE/FITNEE_Client_Refactor pull request #3
Opened 2024-04-21 12:24 UTC by sseho

### 구현 목록
- 홈화면(루틴 있을 경우)
- 홈화면(루틴 없을 경우)
- 템플릿.tsx
- createRoutine svg 추가
- CreateRoutine1 구현
- 루틴 생성 화면 컴포넌트로 분리
- progressBar 컴포넌트
- progressBar 맨 앞에서부터 시작으로 변경

2024-04-21 15:02 UTC, leejin-rho approved these changes

2024-04-24 19:14 UTC, iOdiO89 requested changes
1. 필요없는 주석들 삭제해주시고

2. 여러 화면들 다 대응해야 하니까 화면 전체 layout은 justify-between으로 설정해주세용

3. 가끔 `width: __ %` 로 되어있는 게 있던데 정확한 px 값으로 padding 기입 부탁드립니다 ㅠㅅㅠ ..

4. develop 한번 더 풀 받아주세용 `/src/pages` 안에 폴더명을 다 소문자로 설정해놨었는데 그게 깃허브에서 대문자로 올려줘서 .. 다시 소문자로 설정했습니닷 폴더명때문에 conflict 날 수 있으니까 신경써서 봐주세요!

나머지는 LGTM !!!!!

2024-04-24 19:14 UTC, iOdiO89 commented on src/components/CreateRoutine/ProgressBar.tsx
> +  width: 90%;
이것도 `width: 90%;` 대신에 padding: 0 24px 로 ...!!!!!!

2024-04-24 19:14 UTC, iOdiO89 commented on src/components/Template.tsx
이것은 복붙을 위한 파일 ...? 인가요 필요없는 거면 삭제해주세요

2024-04-24 19:14 UTC, iOdiO89 commented on src/pages/Home/EmptyRoutine.tsx
이 파일은 전체적으로 폰트설정이 안 되어 있는 것 같습니당

2024-05-09 07:02 UTC, iOdiO89 approved these changes

2024-05-09 07:06 UTC, merged