Feature/2 exercise course UI
FITNEE/FITNEE_Client_Refactor pull request #4
Opened 2024-04-21 13:16 UTC by leejin-rho

### 📌 구현 기능

- 운동 전, 운동시작, 운동과정, 휴식시간 UI 및 기능 구현, Dummy Data 생성

### 🛠 작업 내용

- [x] 운동 전 page 기본 UI
- [x] 운동 시작 page 기본 UI
- [x] 운동과정 page 기본 UI
- [x] 휴식 시간 component 기본 UI
- [x] 필요한 Dummy data 및 함수들 구현

2024-04-24 20:02 UTC, iOdiO89 requested changes
1. `width:327px` 같은 거는 양쪽 padding을 고정값으로 주고 `width:100%`로 하는 게 더 좋아보이긴 한데 이건 민언니한테 한 번 더 물어보고 코멘트 달아놓을게!

2. 폰트 설정이 전반적으로 안 되어 있어서 `font-family: 'SemiBold';` 이런 식으로 수정하면 좋을 것 같습니당 

3. develop 한번 더 풀 받아주세용 /src/pages 안에 폴더명을 다 소문자로 설정해놨었는데 그게 깃허브에서 대문자로 올려줘서 .. 다시 소문자로 설정했습니닷 폴더명때문에 conflict 날 수 있으니까 신경써서 봐주세요!

나머지는 다 좋습니다아 LGTM !

2024-04-25 06:00 UTC, leejin-rho commented on src/components/Exercise/BreakScreen.tsx
> +  const RestTime = ({ remainingTime }: any) => {
이거 근데 라이브러리라서 저게 잘 안된다 ㅠ undefined가 나으려나..>?????? 그냥 number로 넣으면 에러가 나

2024-04-25 06:05 UTC, leejin-rho commented on src/components/Exercise/BreakScreen.tsx
웅웅 맞긴한데, 전역으로 관리하는 걸로 바꾸려고..! 일단 기존코드 넣어놨어. 원래는 처음 페이지에서 데이터받아서 그걸 컴포넌트끼리 전달시켰어서 그 방법이 들어가있는...@!

2024-04-25 06:05 UTC, leejin-rho commented on src/components/Exercise/BlurSet.tsx
> +  width: 327px;
오케잉~~!

2024-04-25 06:06 UTC, leejin-rho commented on src/assets/images/SVGs/icon/Check_Disabled.svg
체크 색이 달라..!! 근데 왜인지를 모르겠네...? Check_Disabled가 내가 쓰는 색이 맞아...! Check.svg이거 어디서 쓰이나..?

2024-04-25 06:06 UTC, leejin-rho commented on src/assets/images/SVGs/icon/Check_Disabled.svg
그냥 처음에 와프때 가져온건가..?

2024-04-25 06:06 UTC, leejin-rho commented on src/assets/images/SVGs/icon/Left.svg
그냥 필요할때마다 바꿔두 될거같혀~~!

2024-04-25 06:10 UTC, leejin-rho commented on .prettierrc
웅₩~!
지우고 머지할게

2024-04-25 06:10 UTC, leejin-rho commented on src/assets/images/SVGs/icon/Left.svg
폰트는 내가 그냥 복사해와섴ㅋㅋㅋㅋㅋ 조만간 한번에 수정할게잉

2024-04-25 06:14 UTC, leejin-rho reviewed
.

2024-04-25 11:37 UTC, iOdiO89 approved these changes
리뷰 내용 수정은 다음 branch에서 진행하기로 함

2024-04-25 11:37 UTC, merged